modpackMode = false

[fullscreen]
  mode = "WINDOWED"

  disableBorderlessOptimizations = false

  attachModeF11 = "ATTACH"

[fpsDisplay]
  mode = "ADVANCED"

  align = "LEFT"

  verticalAlign = "TOP"

  systemDetails = "OFF"

  margin = 12

  verticalMargin = 12
  shadow = false

[fog]
  enabled = true
  onOverworld = true
  onNether = true
  onEnd = true
  blueBand = true

  custom = false

  start = 0

  end = 192

  shape = "CYLINDER"

[world]
  cloudsHeight = 192

  chunkFadeSpeed = "SLOW"

  leavesCulling = "OFF"

  lowerVoidHorizon = 63

  farSkybox = true

[nametags]
  entities = true
  players = true
  items = true

[darkness]
  mode = "VANILLA"
  onOverworld = true
  onNether = false

  netherFogBright = 0.5
  onEnd = false

  endFogBright = 0.5

  byDefault = false

  dimensionWhitelist = []
  onNoSkyLight = false
  blockLightOnly = false
  affectedByMoonPhase = true

  newMoonBright = 0.0

  fullMoonBright = 0.25

[interface]
  hideJREMI = false
  hideJREMIHint = false
  fontShadows = true
  fastLanguageReload = true

  settingsScreen = "SODIUM"

[fastBlocks]
  chests = false
  beds = false

[particles]
  rain = true
  rainDrops = true
  blockCracking = true
  blockDestroyed = true

  disabled = []

[culling]
  tileEntities = true

  tileEntityDistanceX = 4096

  tileEntityDistanceY = 32
  entities = true

  entityLimit = 512

  entityDistanceX = 4096

  entityDistanceY = 32
  monsters = false

  monsterDistanceX = 16384

  monsterDistanceY = 64

  entityWhitelist = [
    "minecraft:ghast",
    "minecraft:ender_dragon",
    "iceandfire:all",
    "create:all"
  ]

  monsterWhitelist = []

  tileEntityWhitelist = [
    "waterframes:all"
  ]

[zoom]
  enabled = true

  max = 50.0
