compactFastMap = false
useSmallThreadingDetector = false
cacheMultipartPredicates = true
multipartDeduplication = true
blockstateCacheDeduplication = true
dataComponentPatch = true
modelResourceLocations = true
modelSides = true
replaceNeighborLookup = true
populateNeighborTable = false
replacePropertyMap = true
bakedQuadDeduplication = true
